services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: bss_user
      POSTGRES_PASSWORD: bss_password
      POSTGRES_DB: bss_database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bss_user -d bss_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      DB_USER: bss_user
      DB_PASSWORD: bss_password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bss_database
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: nuxt-client
volumes:
  postgres_data: